"""Run presets for smoke / six-hour / overnight autonomous local runs."""

from __future__ import annotations

from typing import Any

PRESETS: dict[str, dict[str, Any]] = {
    "smoke": {
        "wall_hours": 0.5,
        "max_degree": 6,
        "workers": 1,
        "ram_ceiling_gb": 4.0,
        "checkpoint_minutes": 5,
        "advance_uncertified": False,
        "validate": True,
        "checkpoint_resume_test": True,
        "focus": "6d_ladder",
        "description": "30 minutes, low workers, no progression beyond next uncertified phase; validation + checkpoint/resume test.",
    },
    "degree8": {
        "wall_hours": 2.0,
        "max_degree": 8,
        "workers": 2,
        "ram_ceiling_gb": 8.0,
        "checkpoint_minutes": 10,
        "advance_uncertified": False,
        "validate": True,
        "validate_quick": True,
        "reuse_certified_n8": True,
        # Evaluating all 20 N=8 contraction graphs OOMs/SIGKILLs on this machine.
        # Count is certified (20); paper x^(8) covers the known degree-8 generator.
        "skip_n8_discovery": True,
        "discover_ladder": True,
        "n8_draws": 4,
        "checkpoint_resume_test": False,
        "focus": "6d_degree8",
        "allow_degree8_planning": True,
        "enumerate_degree8": True,
        "description": "6D ladder discovery; N=8 count certified, full 20-graph eval deferred (crash risk).",
    },
    "full": {
        "wall_hours": 6.0,
        "max_degree": 8,
        "workers": 2,
        "ram_ceiling_gb": 10.0,
        "checkpoint_minutes": 10,
        "advance_uncertified": False,
        "validate": True,
        "validate_quick": True,
        "reuse_certified_n8": True,
        "skip_n8_discovery": True,  # same crash guard; paper gens + N<=6 discovery is the 6D answer
        "discover_ladder": True,
        "n8_draws": 4,
        "checkpoint_resume_test": False,
        "focus": "6d_full",
        "allow_degree8_planning": True,
        "enumerate_degree8": True,
        "description": "Full stable 6D pass (5 paper gens + ranks at N=2,4,6; N=8 count only).",
    },
    "six-hour": {
        "wall_hours": 6.0,
        "max_degree": 8,
        "workers": 2,
        "ram_ceiling_gb": 8.0,
        "checkpoint_minutes": 10,
        "advance_uncertified": False,
        "validate": True,
        "checkpoint_resume_test": False,
        "focus": "6d_degree8",
        "enumerate_degree8": True,
        "description": "6 hours on 6D ladder through degree-8; 10D deferred.",
    },
    "overnight": {
        "wall_hours": 12.0,
        "max_degree": 8,
        "workers": 2,
        "ram_ceiling_gb": 12.0,
        "checkpoint_minutes": 10,
        "advance_uncertified": False,
        "require_ac": True,
        "validate": True,
        "checkpoint_resume_test": False,
        "focus": "6d_degree8",
        "enumerate_degree8": True,
        "description": "12 hours, plugged-in required; 6D through degree-8 only (10D deferred).",
    },
    "ten-d": {
        "wall_hours": 6.0,
        "max_degree": 2,
        "workers": 2,
        "ram_ceiling_gb": 8.0,
        "checkpoint_minutes": 5,
        "advance_uncertified": False,
        "validate": True,
        "validate_quick": True,
        "discover_ladder": False,
        "discover_10d": True,
        "checkpoint_resume_test": False,
        "focus": "10d",
        # Full low-order dense discovery OOMs/SIGKILLs — skip; catalog is the climb.
        "skip_low_order": True,
        "low_order_draws": 4,
        "catalog_n_draws": 24,
        "catalog_chunk_sec": 180,
        "skip_catalog": True,
        "wait_for_n8": True,
        "enum_5regular_ns": [2, 4],
        "discover_10d_graphs": True,
        "graph_degrees": [4, 6],
        "graph_n_draws": 32,
        "max_einsum_intermediate": 5.0e7,
        "description": "6h 10D climb: N=4/6 graphs, wait for N=8, skip wasted catalog.",
    },
    "overnight-10d": {
        "wall_hours": 12.0,
        "max_degree": 2,
        "workers": 2,
        "ram_ceiling_gb": 8.0,
        "checkpoint_minutes": 5,
        "advance_uncertified": False,
        "require_ac": True,
        "validate": True,
        "validate_quick": True,
        "discover_ladder": False,
        "discover_10d": True,
        "checkpoint_resume_test": False,
        "focus": "10d",
        "skip_low_order": True,
        "low_order_draws": 4,
        "catalog_n_draws": 32,
        "catalog_chunk_sec": 180,
        "skip_catalog": True,
        "wait_for_n8": True,
        "enum_5regular_ns": [2, 4],
        "discover_10d_graphs": True,
        "graph_degrees": [4, 6],
        "graph_n_draws": 80,
        "n8_climb_degrees": [4, 6, 8, 10],
        "max_einsum_intermediate": 5.0e7,
        "description": "12h 10D: climb N=4/6/8/10 with large samples toward ~81.",
    },
}


def resolve_preset(name: str | None) -> dict[str, Any]:
    if not name:
        return {}
    key = name.strip().lower()
    if key not in PRESETS:
        raise SystemExit(f"Unknown preset {name!r}. Choose: {', '.join(PRESETS)}")
    return dict(PRESETS[key])
